### PR TITLE
Organization & Bugfixes

### PR DESCRIPTION
**Pull request by sme23**
Moves all skill and hack installation config options to `Engine Hacks/Config.event` (some were just "uncomment this installer" in `_MasterHackInstaller.event` before), adds a few skill system-integrated hacks, updates some others. Still WIP.

### CODE REVIEW

**Comment by sme23** [comment]
Moves hack installation config from `_MasterHackInstaller.event` to `Config.event` and reconfigures it to be definition-based installation config and not include-based installation config.
Fixes issue #25.
Updates Escape-Arrive (twice).
Moves proc loop to CalcLoops, as it should have already been there.
Integrates status-inflicting weapons as a configurable hack installation.
Updates various comments referring to filepaths that are no longer existent.
Moves skill csv tables into their own subfolder.
Removes all spaces from filenames in `Engine Hacks` and `Events`.
Changes all .asm source files in `Engine Hacks` to .s.
Standardizes all `[NL]` in text to `[N]`.

**Comment by sme23** [comment]
frick how do I resolve conflicts

**Comment by sme23** [comment]
there we go

**Comment by sme23** [comment]
Fixed issue #116

**Comment by sme23** [comment]
Conflicts resolved with #118.

**Comment by Snakey11** [comment]
Okay I'm gonna green light this. The organization seems fine, and I tested the game. Nothing's exploding. This is kind of a monumental thing for testing everything, but I did some basic stuff, and everything seems to be okay. Really it's about time we pull the trigger and put this PR to rest please.

**Comment by StanHash** [comment]
Imma merge. Any issues that would be left can be reported as they usually are and dealt with in other prs

**Pull request merged**
