### PR TITLE
Passive Item Skills

### PR DESCRIPTION
**Pull request by Teraspark**
added passive item skills to skilltester

fixed the check for the equipped weapon's skill and the conflict with shadowgift type skills

added a item skill getter

### CODE REVIEW

**Comment by sme23** [comment]
New features tested and working properly as far as I can tell

**Comment by Snakey11** [comment]
There appears to be significant lag when running battle calcs. I've got 3 examples:
ezgif com-optimize (1)
Loading units takes a fat minute. I know this is a lot of units, but still.
qa31eS5K5c
There's enough of a pause for battle calcs that the class and character names flash in and out on the stat screen.
Oc9TETpqi2
There's a noticeable pause in the attack menu. It's noticeable especially since Ephraim's face is loaded before the stat display below which isn't vanilla behavior.
The system seems fine, but the lag is pretty bad. Sorry, Tera. :(

**Comment by Teraspark** [comment]
This update should fix the lag let me know if it works

**Comment by sme23** [comment]
Everything seems to be in order, lag issues are at least somewhat mitigated but i'm also bad at telling lag
Gy6Jwhv4tS

**Comment by sme23** [comment]
Actually, shadowgift may be broken? Eirika doesn't meet the requirements for shadowgift to be useful as she has no magic rank but giving flux shadowgift as an item skill will allow her to use flux

**Comment by sme23** [comment]
Shadowgift being broken is not the fault of this PR, fixed with #156. Given this, everything else here looks fine and can be merged imo.

**Pull request merged**
